package upv.etsinf.ipc.black;

import java.util.ArrayList;
import java.util.Random;

import com.trolltech.qt.gui.QPixmap;

public class Baraja {
	
	ArrayList<Carta> baraja = new ArrayList<>();
	public Baraja() {
		QPixmap Carta49 = new QPixmap("classpath:icons/2s.png");
	    Carta twos = new Carta(Carta49, 2,"spade", "Two");    
	    QPixmap Carta45 = new QPixmap("classpath:icons/3s.png");
	    Carta threes = new Carta(Carta45, 3,"spade", "Three");
	    QPixmap Carta1 = new QPixmap("classpath:icons/4s.png");
	    Carta fours = new Carta(Carta1, 4, "spade","Four");  
	    QPixmap Carta13 = new QPixmap("classpath:icons/5s.png");
	    Carta fives = new Carta(Carta13, 5, "spade", "Five");
	    QPixmap Carta27 = new QPixmap("classpath:icons/6s.png");
	    Carta sixs = new Carta(Carta27, 6, "spade", "Six");
	    QPixmap Carta9 = new QPixmap("classpath:icons/7s.png");
	    Carta sevens = new Carta(Carta9, 7, "spade" , "Seven");
	    QPixmap Carta17 = new QPixmap("classpath:icons/8s.png");
	    Carta eights = new Carta(Carta17, 8, "spade", "Eight");
	    QPixmap Carta40 = new QPixmap("classpath:icons/9s.png");
	    Carta nines = new Carta(Carta40, 9,"spade", "Nine");
	    QPixmap Carta50 = new QPixmap("classpath:icons/10s.png");
	    Carta tens = new Carta(Carta50, 10,"spade", "Ten");
	    QPixmap Carta26 = new QPixmap("classpath:icons/jacks.png");
	    Carta jacks = new Carta(Carta26, 10, "spade", "Jack");
	    QPixmap Carta33 = new QPixmap("classpath:icons/queens.png");
	    Carta queens = new Carta(Carta33, 10,"spade", "Queen");
	    QPixmap Carta18 = new QPixmap("classpath:icons/kings.png");
	    Carta kings = new Carta(Carta18, 10, "spade", "King");
	    QPixmap Carta15 = new QPixmap("classpath:icons/aces.png");
	    Carta aces = new Carta(Carta15, 11, "spade", "Ace");

	    QPixmap Carta39 = new QPixmap("classpath:icons/2h.png");
	    Carta twoh = new Carta(Carta39, 2,"heart", "Two");
	    QPixmap Carta2 = new QPixmap("classpath:icons/3h.png");
	    Carta threeh = new Carta(Carta2, 3, "heart","Three");
	    QPixmap Carta8 = new QPixmap("classpath:icons/4h.png");
	    Carta fourh = new Carta(Carta8, 4, "heart", "Four");
	    QPixmap Carta51 = new QPixmap("classpath:icons/5h.png");
	    Carta fiveh = new Carta(Carta51, 5,"heart", "Five");
	    QPixmap Carta24 = new QPixmap("classpath:icons/6h.png");
	    Carta sixh = new Carta(Carta24, 6,"heart", "Six");
	    QPixmap Carta34 = new QPixmap("classpath:icons/7h.png");
	    Carta sevenh = new Carta(Carta34, 7,"heart", "Seven");
	    QPixmap Carta35 = new QPixmap("classpath:icons/8h.png");
	    Carta eighth = new Carta(Carta35, 8,"heart", "Eight");
	    QPixmap Carta4 = new QPixmap("classpath:icons/9h.png");
	    Carta nineh = new Carta(Carta4, 9, "heart","Nine");
	    QPixmap Carta7 = new QPixmap("classpath:icons/10h.png");
	    Carta tenh = new Carta(Carta7, 10,"heart", "Ten");
	    QPixmap Carta3 = new QPixmap("classpath:icons/jackh.png");
	    Carta jackh = new Carta(Carta3, 10, "heart","Jack");
	    QPixmap Carta25 = new QPixmap("classpath:icons/queenh.png");
	    Carta queenh = new Carta(Carta25, 10,"heart", "Queen");
	    QPixmap Carta36 = new QPixmap("classpath:icons/kingh.png");
	    Carta kingh = new Carta(Carta36, 10,"heart", "King");
	    QPixmap Carta10 = new QPixmap("classpath:icons/aceh.png");
	    Carta aceh = new Carta(Carta10, 11, "heart", "Ace");

	    QPixmap Carta31 = new QPixmap("classpath:icons/2d.png");
	    Carta twod = new Carta(Carta31, 2,"diamond", "Two");
	    QPixmap Carta30 = new QPixmap("classpath:icons/3d.png");
	    Carta threed = new Carta(Carta30, 3,"diamond", "Three");
	    QPixmap Carta32 = new QPixmap("classpath:icons/4d.png");
	    Carta fourd = new Carta(Carta32, 4,"diamond", "Four");
	    QPixmap Carta48 = new QPixmap("classpath:icons/5d.png");
	    Carta fived = new Carta(Carta48, 5,"diamond", "Five");
	    QPixmap Carta5 = new QPixmap("classpath:icons/6d.png");
	    Carta sixd = new Carta(Carta5, 6, "diamond", "Six");
	    QPixmap Carta41 = new QPixmap("classpath:icons/7d.png");
	    Carta sevend = new Carta(Carta41, 7,"diamond", "Seven ");
	    QPixmap Carta14 = new QPixmap("classpath:icons/8d.png");
	    Carta eightd = new Carta(Carta14, 8, "diamond", "Eight");
	    QPixmap Carta16 = new QPixmap("classpath:icons/9d.png");
	    Carta nined = new Carta(Carta16, 9, "diamond", "Nine");
	    QPixmap Carta12 = new QPixmap("classpath:icons/10d.png");
	    Carta tend = new Carta(Carta12, 10, "diamond", "Ten");    
	    QPixmap Carta11 = new QPixmap("classpath:icons/jackd.png");
	    Carta jackd = new Carta(Carta11, 10, "diamond", "Jack");
	    QPixmap Carta6 = new QPixmap("classpath:icons/queend.png");
	    Carta queend = new Carta(Carta6, 10, "diamond", "Queen");
	    QPixmap Carta47 = new QPixmap("classpath:icons/kingd.png");
	    Carta kingd = new Carta(Carta47, 10,"diamond", "King");
	    QPixmap Carta20 = new QPixmap("classpath:icons/aced.png");
	    Carta aced = new Carta(Carta20, 11,"diamond", "Ace");

	    QPixmap Carta28 = new QPixmap("classpath:icons/2c.png");
	    Carta twoc = new Carta(Carta28, 2,"club", "Two");
	    QPixmap Carta38 = new QPixmap("classpath:icons/3c.png");
	    Carta threec = new Carta(Carta38, 3,"club", "Three");
	    QPixmap Carta19 = new QPixmap("classpath:icons/4c.png");
	    Carta fourc = new Carta(Carta19, 4,"club", "Four");
	    QPixmap Carta21 = new QPixmap("classpath:icons/5c.png");
	    Carta fivec = new Carta(Carta21, 5,"club", "Five");
	    QPixmap Carta43 = new QPixmap("classpath:icons/6c.png");
	    Carta sixc = new Carta(Carta43, 6,"club", "Six");
	    QPixmap Carta42 = new QPixmap("classpath:icons/7c.png");
	    Carta sevenc = new Carta(Carta42, 7,"club", "Seven");
	    QPixmap Carta22 = new QPixmap("classpath:icons/8c.png");
	    Carta eightc = new Carta(Carta22, 8,"club", "Eight");
	    QPixmap Carta23 = new QPixmap("classpath:icons/9c.png");
	    Carta ninec = new Carta(Carta23, 9,"club", "Nine");
	    QPixmap Carta44 = new QPixmap("classpath:icons/10c.png");
	    Carta tenc = new Carta(Carta44, 10,"club", "Ten");   
	    QPixmap Carta29 = new QPixmap("classpath:icons/jackc.png");
	    Carta jackc = new Carta(Carta29, 10,"club", "Jack");
	    QPixmap Carta52 = new QPixmap("classpath:icons/queenc.png");
	    Carta queenc = new Carta(Carta52, 10,"club", "Queen");
	    QPixmap Carta46 = new QPixmap("classpath:icons/kingc.png");
	    Carta kingc = new Carta(Carta46, 10,"club", "King");
	    QPixmap Carta37 = new QPixmap("classpath:icons/acec.png");
	    Carta acec = new Carta(Carta37, 11,"club", "Ace");

	    baraja.add(acec);
	    baraja.add(threeh);
	    baraja.add(aces);
	    baraja.add(jackh);
	    baraja.add(nineh);
	    baraja.add(sixd);
	    baraja.add(queend);
	    baraja.add(aceh);
	    baraja.add(nined);
	    baraja.add(fours);
	    baraja.add(fourh);
	    baraja.add(aced);
	    baraja.add(sevens);
	    baraja.add(tenh);
	    baraja.add(jackd);
	    baraja.add(tend);
	    baraja.add(fives);
	    baraja.add(eightd);
	    baraja.add(eights);
	    baraja.add(kings);
	    baraja.add(fourc);
	    baraja.add(fivec);
	    baraja.add(eightc);
	    baraja.add(ninec);
	    baraja.add(sixh);
	    baraja.add(queenh);
	    baraja.add(jacks);
	    baraja.add(sixs);
	    baraja.add(twoc);
	    baraja.add(jackc);
	    baraja.add(threed);
	    baraja.add(twod);
	    baraja.add(fourd);
	    baraja.add(queens);
	    baraja.add(sevenh);
	    baraja.add(eighth);
	    baraja.add(kingh);
	    baraja.add(threec);
	    baraja.add(twoh);
	    baraja.add(nines);
	    baraja.add(sevend);
	    baraja.add(sevenc);
	    baraja.add(sixc);
	    baraja.add(tenc);
	    baraja.add(threes);
	    baraja.add(kingc);
	    baraja.add(kingd);
	    baraja.add(fived);
	    baraja.add(twos);
	    baraja.add(tens);
	    baraja.add(fiveh);
	    baraja.add(queenc);	
	}
	
	public Carta getCarta() {
		Random rand = new Random();
		Carta result = new Carta();
		int x = rand.nextInt(baraja.size());
		result = baraja.remove(x);
		return result;

	}
}
